source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target ‘CRMMobile’ do
pod 'MBProgressHUD', '~> 1.0.0'
pod 'AFNetworking'
pod 'SDCycleScrollView','~> 1.64'
pod 'AFNetworking'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'Masonry'
pod 'MJExtension'
pod 'YYCache'
end
